spring:
  application:
    name: nt-gateway
---
server:
  port: 9001
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:nt-gateway.jks
    key-store-password: jaypatel
    key-alias: nt-gateway
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:nt-gateway.jks
    trust-store-password: jaypatel
    trust-store-type: JKS
---
endpoint:
  ms-service: https://localhost:9002/nt-ms/data


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
